name: Keep Render Server Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          echo "Pinging Render..."
          curl -s -o /dev/null -w "%{http_code}\n" https://lumoshub-backend.onrender.com/ping
